# Generated by Django 3.1.4 on 2020-12-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sutdent',
            name='clas',
        ),
    ]
