# Generated by Django 3.1.4 on 2020-12-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0002_remove_sutdent_clas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sutdent',
            new_name='Student',
        ),
    ]
