# Generated by Django 3.1.4 on 2021-01-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='smmary',
            new_name='summary',
        ),
    ]
